"""Qdrant vector database service for furniture similarity search.

This module provides similarity search functionality using Qdrant vector database
and CLIP embeddings generated by the Lambda service.
"""
import logging
from PIL import Image

from backend.core.config import Config
from backend.services.clip_service import LambdaCLIPService

logger = logging.getLogger(__name__)


class QdrantService:
    """Adapter implementing furniture search using Qdrant vector database.

    Loads image embeddings and metadata from a remote Qdrant instance
    to support similarity search via the remote `LambdaCLIPService`.
    """

    def __init__(self, lambda_service: LambdaCLIPService | None = None):
        logger.info("Initializing Search Engine (Qdrant adapter)...")
        self.clip_service = lambda_service or LambdaCLIPService()

        # Defaults if initialization fails
        self.qdrant_client = None
        self.is_initialized = False

        try:
            from qdrant_client import QdrantClient
            from qdrant_client.models import Distance, VectorParams

            # Validate configuration
            if not Config.QDRANT_URL:
                logger.error("QDRANT_URL not configured")
                return

            if not Config.QDRANT_API_KEY:
                logger.error("QDRANT_API_KEY not configured")
                return

            # Initialize Qdrant client
            logger.info("Connecting to Qdrant at: %s", Config.QDRANT_URL)
            self.qdrant_client = QdrantClient(
                url=Config.QDRANT_URL,
                api_key=Config.QDRANT_API_KEY,
                timeout=30,  # Increase timeout to 30 seconds
                prefer_grpc=False
                
            )

            # Verify connection and collection exists
            collections = self.qdrant_client.get_collections()
            collection_names = [col.name for col in collections.collections]

            if Config.QDRANT_COLLECTION_NAME not in collection_names:
                logger.error(
                    "Collection '%s' not found in Qdrant. Available collections: %s",
                    Config.QDRANT_COLLECTION_NAME,
                    collection_names
                )
                return

            # Get collection info to verify it has embeddings
            collection_info = self.qdrant_client.get_collection(Config.QDRANT_COLLECTION_NAME)
            logger.info(
                "Successfully connected to collection '%s' with %d points",
                Config.QDRANT_COLLECTION_NAME,
                collection_info.points_count
            )

            self.is_initialized = True
            logger.info("Search Engine initialized successfully with Qdrant.")

        except Exception as e:
            logger.exception("CRITICAL ERROR initializing Qdrant search: %s", str(e))
            self.qdrant_client = None
            self.is_initialized = False

    def search(self, image_input, top_k: int = 4):
        """Search for similar furniture items using remote CLIP embedding and Qdrant.
        
        Args:
            image_input: PIL Image or file path
            top_k: Number of results to return
            
        Returns:
            list: Array of furniture items with metadata
        """
        logger.info("DEBUG : innit search for furniture items...")
        if not self.is_initialized or self.qdrant_client is None:
            logger.warning("Search service: Qdrant not initialized. Cannot perform search.")
            raise RuntimeError("Qdrant search service not initialized")

        if self.clip_service is None:
            logger.warning("Search service: CLIP service not initialized. Ensure LAMBDA_CLIP_URL is configured.")
            raise RuntimeError("CLIP service not initialized")

        try:
            # Normalize input to PIL Image
            if isinstance(image_input, str):
                image = Image.open(image_input).convert('RGB')
            else:
                image = image_input.convert('RGB')

            # Generate embedding via Lambda CLIP
            logger.info("Generating CLIP embedding via Lambda CLIP")
            query_embedding = self.clip_service.get_image_embedding(image)

            import numpy as _np

            query_embedding = _np.array(query_embedding, dtype=_np.float32)
            query_embedding = query_embedding / (_np.linalg.norm(query_embedding) + 1e-8)
            query_embedding = query_embedding.tolist()

            # Search in Qdrant
            logger.info("Searching Qdrant for similar furniture")
            search_results = self.qdrant_client.query_points(
                collection_name=Config.QDRANT_COLLECTION_NAME,
                query=query_embedding,
                limit=top_k,
                with_payload=True
            )

            results = []
            for hit in search_results.points:
                try:
                    payload = hit.payload or {}
                    score = hit.score

                    # Extract metadata from payload
                    title = payload.get('title') or payload.get('name', 'Unknown Item')
                    result_item = {
                        'score': float(score),
                        'title': title,
                        'price': str(payload.get('price', 'N/A')),
                        'source': payload.get('source', ''),
                        'image_url': payload.get('image_url', ''),
                        'search_query': f"{title} {payload.get('source', '')}"
                    }
                    results.append(result_item)

                except Exception as e:
                    logger.exception("Error processing search result: %s", str(e))
                    continue

            logger.info("Found %d results for furniture search", len(results))
            return results

        except Exception as e:
            logger.exception("Error during furniture search: %s", str(e))
            return []
